name: Apply Rules

on:
  push:
    branches:
      - master
    paths:
      - 'rules/rules.csv'
  workflow_dispatch:

permissions:
  id-token: write # required for OIDC authentication
  contents: read

jobs:
  apply-rules:
    name: Import rules to DynamoDB
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build rudolph CLI
        run: go build -o rudolph-cli ./cmd/cli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::813924112385:role/GitHubAssumeRole
          aws-region: us-east-1

      - name: Import rules
        run: ENV=production ./rudolph-cli rules import -f rules/rules.csv
